ktor :
    deployment:
        port: "$PORT:8080"
    application:
        modules:
        - [ com.example.ApplicationKt.module ]


jwt :
    domain: "https://online.muhammadali.kite"
    audience: "kite-jwt-audience"
    realm: "kite"
